version: '3.2'

services:
  postgres:
    image: postgres:15.3
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  pgadmin:
    profiles:
      - db_debug
    depends_on:
      - postgres
    image: dpage/pgadmin4
    ports:
      - 80:80
      - 443:443
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DEFAULT_EMAIL=abc@def.com
  metabase:
    depends_on:
      - postgres
    ports:
      - 3000:3000
    image: metabase/metabase:latest
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - metabasedb:/metabase-data/
  backend:
    depends_on:
      - postgres
    image: node:18-alpine3.17
    ports:
      - 12345:12345
    volumes:
      - ./:/app
    command: npm start
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=impacthack
    working_dir: /app
  backend-init:
    image: node:18-alpine3.17
    profiles:
      - setup
    working_dir: /app
    volumes:
      - ./:/app
    command: npm install
volumes:
  postgres:
  pgadmin:
  metabasedb: